[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 302
  conditions = {Role = ["visitor"]}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["member"]}
