[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/home.html"
  to = "/login.html"
  status = 302
  force = true
  conditions = {Role = ["visitor"]}

[[redirects]]
  from = "/objects.html"
  to = "/login.html"
  status = 302
  force = true
  conditions = {Role = ["visitor"]}

[[redirects]]
  from = "/debates.html"
  to = "/login.html"
  status = 302
  force = true
  conditions = {Role = ["visitor"]}

[[redirects]]
  from = "/elus.html"
  to = "/login.html"
  status = 302
  force = true
  conditions = {Role = ["visitor"]}

[[redirects]]
  from = "/stats.html"
  to = "/login.html"
  status = 302
  force = true
  conditions = {Role = ["visitor"]}
